#!/usr/bin/env python3
"""
固件编译模块 - 负责 Klipper 固件编译
"""
import os
import subprocess
import shutil
import json
from pathlib import Path

class FirmwareCompiler:
    def __init__(self, klipper_path='~/klipper'):
        self.klipper_path = os.path.expanduser(klipper_path)
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.configs_dir = os.path.join(base_dir, 'configs')
        self.bl_firmwares_dir = os.path.join(base_dir, 'bl_firmwares')
        
    def check_dependencies(self):
        """检查 Klipper依赖"""
        deps = {
            'klipper': False,
            'gcc_arm': False,
            'python_deps': False
        }
        
        # 检查 Klipper 目录
        if os.path.exists(self.klipper_path):
            deps['klipper'] = True
        
        # 检查 ARM GCC 编译器
        try:
            result = subprocess.run(['arm-none-eabi-gcc', '--version'], 
                                  capture_output=True, text=True)
            if result.returncode == 0:
                deps['gcc_arm'] = True
        except:
            pass
        
        # 检查 Python 依赖
        try:
            import serial
            import usb
            deps['python_deps'] = True
        except:
            pass
        
        return deps
    
    def install_dependencies(self):
        """安装 Klipper依赖"""
        try:
            # 安装系统依赖
            subprocess.run(['sudo', 'apt-get', 'update'], check=True)
            subprocess.run(['sudo', 'apt-get', 'install', '-y', 
                          'gcc-arm-none-eabi', 'binutils-arm-none-eabi'], 
                         check=True)
            
            # 安装 Python 依赖
            subprocess.run(['pip3', 'install', 'pyserial', 'pyusb'], 
                         check=True)
            
            return True, "依赖安装成功"
        except Exception as e:
            return False, f"安装失败：{e}"
    
    def compile_firmware(self, config_data, flash_mode='DFU'):
        """
        编译固件
        config_data: 配置数据（包含 MCU、晶振等）
        flash_mode: 烧录模式 (DFU, KAT, UF2, CAN 等)
        """
        mcu = config_data.get('处理器', '')
        crystal = config_data.get('晶振', '8 MHz crystal')
        bl_offset = config_data.get('BL 偏移', '16KiB bootloader')
        
        # 生成 .config 文件
        config_content = self._generate_klipper_config(mcu, crystal, bl_offset, flash_mode)
        
        config_path = os.path.join('/tmp', 'firmware_config')
        with open(config_path, 'w') as f:
            f.write(config_content)
        
        # 复制配置到 Klipper
        klipper_config = os.path.join(self.klipper_path, '.config')
        shutil.copy2(config_path, klipper_config)
        
        # 清理并编译
        try:
            # make clean
            subprocess.run(['make', 'clean'], 
                         cwd=self.klipper_path, 
                         capture_output=True, 
                         check=True)
            
            # make menuconfig (使用预生成的配置)
            # 跳过，因为已经复制了.config
            
            # make
            result = subprocess.run(['make', '-j4'], 
                                  cwd=self.klipper_path, 
                                  capture_output=True, 
                                  text=True,
                                  timeout=300)
            
            if result.returncode != 0:
                return False, f"编译失败：{result.stderr}", None
            
            # 查找生成的固件
            firmware_path = self._find_firmware_file(flash_mode)
            
            return True, "编译成功", firmware_path
            
        except subprocess.TimeoutExpired:
            return False, "编译超时", None
        except Exception as e:
            return False, f"编译错误：{e}", None
    
    def _generate_klipper_config(self, mcu, crystal, bl_offset, flash_mode):
        """生成 Klipper .config 文件内容"""
        # 基础配置
        config_lines = [
            "# Automatically generated by Firmware-Tool",
            "CONFIG_STM32F405=y" if 'STM32F4' in mcu else "CONFIG_STM32F446=y",
            "CONFIG_STM32_FLASH=y",
            "",
            "# Bootloader offset",
        ]
        
        # BL 偏移
        if '16KiB' in bl_offset:
            config_lines.append("CONFIG_STM32_BOOTLOADER_SIZE_16K=y")
        elif '32KiB' in bl_offset:
            config_lines.append("CONFIG_STM32_BOOTLOADER_SIZE_32K=y")
        elif '8KiB' in bl_offset:
            config_lines.append("CONFIG_STM32_BOOTLOADER_SIZE_8K=y")
        else:
            config_lines.append("CONFIG_STM32_BOOTLOADER_SIZE_16K=y")
        
        # 晶振频率
        config_lines.append("")
        config_lines.append("# Crystal frequency")
        if '8 MHz' in crystal:
            config_lines.append("CONFIG_STM32_FREQ_8MHZ=y")
        elif '12 MHz' in crystal:
            config_lines.append("CONFIG_STM32_FREQ_12MHZ=y")
        elif '25 MHz' in crystal:
            config_lines.append("CONFIG_STM32_FREQ_25MHZ=y")
        
        # 烧录模式相关配置
        config_lines.append("")
        config_lines.append("# Communication method")
        if flash_mode in ['DFU', 'KAT']:
            config_lines.append("CONFIG_STM32_USB=y")
            config_lines.append("CONFIG_STM32_USB_PA11_PA12=y")
        elif flash_mode == 'CAN':
            config_lines.append("CONFIG_STM32_CANBUS=y")
            config_lines.append("CONFIG_CAN_BUS_SPEED_500K=y")
        
        return '\n'.join(config_lines)
    
    def _find_firmware_file(self, flash_mode):
        """查找编译生成的固件文件"""
        out_dir = os.path.join(self.klipper_path, 'out')
        
        # 查找 bin 文件
        for f in os.listdir(out_dir):
            if f.endswith('.bin'):
                return os.path.join(out_dir, f)
        
        return None
    
    def upload_bl_firmware(self, file, manufacturer='FLY'):
        """上传 BL 固件"""
        try:
            # 确保目录存在
            bl_dir = os.path.join(self.bl_firmwares_dir, manufacturer)
            os.makedirs(bl_dir, exist_ok=True)
            
            # 保存文件
            save_path = os.path.join(bl_dir, file.filename)
            file.save(save_path)
            
            return True, save_path
        except Exception as e:
            return False, str(e)
    
    def get_compiled_firmwares(self, manufacturer='FLY'):
        """获取已编译的固件列表"""
        firmwares = []
        
        # 扫描 configs 目录
        mfr_dir = os.path.join(self.configs_dir, manufacturer)
        if not os.path.exists(mfr_dir):
            return firmwares
        
        for board_type in os.listdir(mfr_dir):
            type_dir = os.path.join(mfr_dir, board_type)
            if not os.path.isdir(type_dir):
                continue
            
            for config_file in os.listdir(type_dir):
                if not config_file.endswith('.json'):
                    continue
                
                config_path = os.path.join(type_dir, config_file)
                try:
                    with open(config_path, 'r') as f:
                        config = json.load(f)
                    
                    # 检查是否有编译输出
                    board_id = config.get('id', config_file.replace('.json', ''))
                    out_dir = os.path.join(self.klipper_path, 'out')
                    
                    # 查找对应的固件文件
                    for f in os.listdir(out_dir):
                        if f.startswith(board_id) or f.endswith('.bin'):
                            firmwares.append({
                                'name': config.get('名称', board_id),
                                'type': board_type,
                                'file': f,
                                'path': os.path.join(out_dir, f)
                            })
                except:
                    continue
        
        return firmwares
